// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SolidarMap.Connection;

#nullable disable

namespace SolidarMap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SolidarMap.Models.Ajuda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AJUDA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_PUBLICACAO");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("DESCRICAO");

                    b.Property<int>("RecursoId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECURSO");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("STATUS");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("RecursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_SMP_AJUDAS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AVALIACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AjudaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AJUDA");

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("COMENTARIO");

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AVALIACAO");

                    b.Property<int>("Nota")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("NOTA");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("AjudaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_SMP_AVALIACOES_C");
                });

            modelBuilder.Entity("SolidarMap.Models.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_LOCALIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AjudaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AJUDA");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(12, 8)
                        .HasColumnType("DECIMAL(12,8)")
                        .HasColumnName("LONGITUDE");

                    b.Property<int>("ZonaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONA");

                    b.HasKey("Id");

                    b.HasIndex("AjudaId");

                    b.HasIndex("ZonaId");

                    b.ToTable("T_SMP_LOCALIZACOES_C");
                });

            modelBuilder.Entity("SolidarMap.Models.Mensagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_MENSAGEM");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AjudaId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_AJUDA");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("MENSAGEM");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_ENVIO");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("AjudaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("T_SMP_MENSAGENS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoRecurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_RECURSO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Recurso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("RECURSO");

                    b.HasKey("Id");

                    b.ToTable("T_SMP_TIPO_RECURSOS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NomeTipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME_TIPO");

                    b.HasKey("Id");

                    b.ToTable("T_SMP_TIPO_USUARIOS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoZona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_ZONA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("ZONA");

                    b.HasKey("Id");

                    b.ToTable("T_SMP_TIPO_ZONAS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CRIACAO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("NVARCHAR2(256)")
                        .HasColumnName("SENHA");

                    b.Property<int>("TipoUsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_TIPO_USUARIO");

                    b.HasKey("Id");

                    b.HasIndex("TipoUsuarioId");

                    b.ToTable("T_SMP_USUARIOS_C");
                });

            modelBuilder.Entity("SolidarMap.Models.Ajuda", b =>
                {
                    b.HasOne("SolidarMap.Models.TipoRecurso", "TipoRecurso")
                        .WithMany("Ajudas")
                        .HasForeignKey("RecursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolidarMap.Models.Usuario", "Usuario")
                        .WithMany("Ajudas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoRecurso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolidarMap.Models.Avaliacao", b =>
                {
                    b.HasOne("SolidarMap.Models.Ajuda", "Ajuda")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("AjudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolidarMap.Models.Usuario", "Usuario")
                        .WithMany("Avaliacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ajuda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolidarMap.Models.Localizacao", b =>
                {
                    b.HasOne("SolidarMap.Models.Ajuda", "Ajuda")
                        .WithMany("Localizacoes")
                        .HasForeignKey("AjudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolidarMap.Models.TipoZona", "TipoZona")
                        .WithMany("Localizacoes")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ajuda");

                    b.Navigation("TipoZona");
                });

            modelBuilder.Entity("SolidarMap.Models.Mensagem", b =>
                {
                    b.HasOne("SolidarMap.Models.Ajuda", "Ajuda")
                        .WithMany("Mensagens")
                        .HasForeignKey("AjudaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SolidarMap.Models.Usuario", "Usuario")
                        .WithMany("Mensagens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ajuda");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SolidarMap.Models.Usuario", b =>
                {
                    b.HasOne("SolidarMap.Models.TipoUsuario", "TipoUsuario")
                        .WithMany("Usuarios")
                        .HasForeignKey("TipoUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoUsuario");
                });

            modelBuilder.Entity("SolidarMap.Models.Ajuda", b =>
                {
                    b.Navigation("Avaliacoes");

                    b.Navigation("Localizacoes");

                    b.Navigation("Mensagens");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoRecurso", b =>
                {
                    b.Navigation("Ajudas");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoUsuario", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SolidarMap.Models.TipoZona", b =>
                {
                    b.Navigation("Localizacoes");
                });

            modelBuilder.Entity("SolidarMap.Models.Usuario", b =>
                {
                    b.Navigation("Ajudas");

                    b.Navigation("Avaliacoes");

                    b.Navigation("Mensagens");
                });
#pragma warning restore 612, 618
        }
    }
}
